version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: flywise
      POSTGRES_PASSWORD: flywise
      POSTGRES_DB: flywise
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      POSTGRES_URL: postgresql://flywise:flywise@db:5432/flywise
      GEMINI_API_KEY: your_key_here
    ports:
      - "8000:8000"
    depends_on:
      - db